"""Create complete Angelix database schema

Revision ID: f66a23c206c1
Revises: 
Create Date: 2026-09-21 19:11:11.692485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f66a23c206c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('organization_type', sa.String(length=50), nullable=False),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('tax_identifier', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_number'),
    sa.UniqueConstraint('tax_identifier')
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_organizations_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_organizations_name'), ['name'], unique=False)

    op.create_table('system_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('logger_name', sa.String(length=150), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('exception_type', sa.String(length=255), nullable=True),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('endpoint', sa.String(length=255), nullable=True),
    sa.Column('method', sa.String(length=20), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_logs_level'), ['level'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_logs_logger_name'), ['logger_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_logs_request_id'), ['request_id'], unique=False)

    op.create_table('token_blocklist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('token_type', sa.String(length=20), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('token_blocklist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_token_blocklist_jti'), ['jti'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_organization_id'), ['organization_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_resource_id'), ['resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_resource_type'), ['resource_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('chatbot_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(length=150), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chatbot_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chatbot_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_chatbot_messages_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chatbot_messages_user_id'), ['user_id'], unique=False)

    op.create_table('financial_statements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('statement_type', sa.String(length=50), nullable=False),
    sa.Column('period_type', sa.String(length=20), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=True),
    sa.Column('source_filename', sa.String(length=255), nullable=True),
    sa.Column('source_file_hash', sa.String(length=128), nullable=True),
    sa.Column('processing_status', sa.String(length=50), nullable=False),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_revenue', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_expenses', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('net_profit', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_assets', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_liabilities', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_equity', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('financial_statements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_financial_statements_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_statements_fiscal_year'), ['fiscal_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_statements_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_statements_period_end'), ['period_end'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_statements_period_start'), ['period_start'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_statements_period_type'), ['period_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_statements_processing_status'), ['processing_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_statements_source_file_hash'), ['source_file_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_statements_statement_type'), ['statement_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_statements_uploaded_by'), ['uploaded_by'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_notification_type'), ['notification_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('generated_by', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('report_type', sa.String(length=100), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('generation_error', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('analysis_content', sa.JSON(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('file_format', sa.String(length=20), nullable=True),
    sa.Column('file_hash', sa.String(length=128), nullable=True),
    sa.Column('ai_generated', sa.Boolean(), nullable=False),
    sa.Column('ai_model', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_generated_by'), ['generated_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_report_type'), ['report_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_status'), ['status'], unique=False)

    op.create_table('uploads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_extension', sa.String(length=20), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('file_hash', sa.String(length=128), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=True),
    sa.Column('processing_status', sa.String(length=50), nullable=False),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extracted_text_available', sa.Boolean(), nullable=False),
    sa.Column('extraction_method', sa.String(length=50), nullable=True),
    sa.Column('is_encrypted', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_filename')
    )
    with op.batch_alter_table('uploads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_uploads_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_uploads_document_type'), ['document_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_uploads_file_hash'), ['file_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_uploads_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_uploads_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_uploads_processing_status'), ['processing_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_uploads_uploaded_by'), ['uploaded_by'], unique=False)

    op.create_table('document_extractions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('financial_statement_id', sa.Integer(), nullable=True),
    sa.Column('statement_type', sa.String(length=50), nullable=True),
    sa.Column('period_type', sa.String(length=20), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('fiscal_year', sa.Integer(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('document_type', sa.String(length=50), nullable=True),
    sa.Column('extraction_method', sa.String(length=50), nullable=False),
    sa.Column('processing_status', sa.String(length=50), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['financial_statement_id'], ['financial_statements.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_extractions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_extractions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_extractions_document_type'), ['document_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_extractions_financial_statement_id'), ['financial_statement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_extractions_fiscal_year'), ['fiscal_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_extractions_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_extractions_period_end'), ['period_end'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_extractions_period_start'), ['period_start'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_extractions_period_type'), ['period_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_extractions_processing_status'), ['processing_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_extractions_statement_type'), ['statement_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_extractions_upload_id'), ['upload_id'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('financial_statement_id', sa.Integer(), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('subcategory', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['financial_statement_id'], ['financial_statements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_financial_statement_id'), ['financial_statement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_reference_number'), ['reference_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_transaction_date'), ['transaction_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_transaction_type'), ['transaction_type'], unique=False)

    op.create_table('extraction_candidates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('extraction_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('debit_credit', sa.String(length=20), nullable=True),
    sa.Column('transaction_type', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('subcategory', sa.String(length=100), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('review_status', sa.String(length=50), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('correction_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['extraction_id'], ['document_extractions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('extraction_candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_extraction_candidates_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_extraction_candidates_extraction_id'), ['extraction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_extraction_candidates_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_extraction_candidates_review_status'), ['review_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_extraction_candidates_reviewed_by'), ['reviewed_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_extraction_candidates_transaction_date'), ['transaction_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_extraction_candidates_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('financial_statement_line_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('financial_statement_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('line_item_name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=True),
    sa.Column('section', sa.String(length=100), nullable=True),
    sa.Column('account_type', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('source_description', sa.Text(), nullable=True),
    sa.Column('extraction_candidate_id', sa.Integer(), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['extraction_candidate_id'], ['extraction_candidates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['financial_statement_id'], ['financial_statements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('financial_statement_line_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_financial_statement_line_items_account_type'), ['account_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_statement_line_items_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_statement_line_items_extraction_candidate_id'), ['extraction_candidate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_statement_line_items_financial_statement_id'), ['financial_statement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_statement_line_items_normalized_name'), ['normalized_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_statement_line_items_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_statement_line_items_section'), ['section'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_statement_line_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_financial_statement_line_items_section'))
        batch_op.drop_index(batch_op.f('ix_financial_statement_line_items_organization_id'))
        batch_op.drop_index(batch_op.f('ix_financial_statement_line_items_normalized_name'))
        batch_op.drop_index(batch_op.f('ix_financial_statement_line_items_financial_statement_id'))
        batch_op.drop_index(batch_op.f('ix_financial_statement_line_items_extraction_candidate_id'))
        batch_op.drop_index(batch_op.f('ix_financial_statement_line_items_created_at'))
        batch_op.drop_index(batch_op.f('ix_financial_statement_line_items_account_type'))

    op.drop_table('financial_statement_line_items')
    with op.batch_alter_table('extraction_candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_extraction_candidates_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_extraction_candidates_transaction_date'))
        batch_op.drop_index(batch_op.f('ix_extraction_candidates_reviewed_by'))
        batch_op.drop_index(batch_op.f('ix_extraction_candidates_review_status'))
        batch_op.drop_index(batch_op.f('ix_extraction_candidates_organization_id'))
        batch_op.drop_index(batch_op.f('ix_extraction_candidates_extraction_id'))
        batch_op.drop_index(batch_op.f('ix_extraction_candidates_created_at'))

    op.drop_table('extraction_candidates')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_transaction_type'))
        batch_op.drop_index(batch_op.f('ix_transactions_transaction_date'))
        batch_op.drop_index(batch_op.f('ix_transactions_reference_number'))
        batch_op.drop_index(batch_op.f('ix_transactions_organization_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_financial_statement_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_created_at'))
        batch_op.drop_index(batch_op.f('ix_transactions_category'))

    op.drop_table('transactions')
    with op.batch_alter_table('document_extractions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_extractions_upload_id'))
        batch_op.drop_index(batch_op.f('ix_document_extractions_statement_type'))
        batch_op.drop_index(batch_op.f('ix_document_extractions_processing_status'))
        batch_op.drop_index(batch_op.f('ix_document_extractions_period_type'))
        batch_op.drop_index(batch_op.f('ix_document_extractions_period_start'))
        batch_op.drop_index(batch_op.f('ix_document_extractions_period_end'))
        batch_op.drop_index(batch_op.f('ix_document_extractions_organization_id'))
        batch_op.drop_index(batch_op.f('ix_document_extractions_fiscal_year'))
        batch_op.drop_index(batch_op.f('ix_document_extractions_financial_statement_id'))
        batch_op.drop_index(batch_op.f('ix_document_extractions_document_type'))
        batch_op.drop_index(batch_op.f('ix_document_extractions_created_at'))

    op.drop_table('document_extractions')
    with op.batch_alter_table('uploads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_uploads_uploaded_by'))
        batch_op.drop_index(batch_op.f('ix_uploads_processing_status'))
        batch_op.drop_index(batch_op.f('ix_uploads_organization_id'))
        batch_op.drop_index(batch_op.f('ix_uploads_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_uploads_file_hash'))
        batch_op.drop_index(batch_op.f('ix_uploads_document_type'))
        batch_op.drop_index(batch_op.f('ix_uploads_created_at'))

    op.drop_table('uploads')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_status'))
        batch_op.drop_index(batch_op.f('ix_reports_report_type'))
        batch_op.drop_index(batch_op.f('ix_reports_organization_id'))
        batch_op.drop_index(batch_op.f('ix_reports_generated_by'))
        batch_op.drop_index(batch_op.f('ix_reports_created_at'))

    op.drop_table('reports')
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_expires_at'))

    op.drop_table('password_reset_tokens')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_priority'))
        batch_op.drop_index(batch_op.f('ix_notifications_notification_type'))
        batch_op.drop_index(batch_op.f('ix_notifications_is_read'))
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))

    op.drop_table('notifications')
    with op.batch_alter_table('financial_statements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_financial_statements_uploaded_by'))
        batch_op.drop_index(batch_op.f('ix_financial_statements_statement_type'))
        batch_op.drop_index(batch_op.f('ix_financial_statements_source_file_hash'))
        batch_op.drop_index(batch_op.f('ix_financial_statements_processing_status'))
        batch_op.drop_index(batch_op.f('ix_financial_statements_period_type'))
        batch_op.drop_index(batch_op.f('ix_financial_statements_period_start'))
        batch_op.drop_index(batch_op.f('ix_financial_statements_period_end'))
        batch_op.drop_index(batch_op.f('ix_financial_statements_organization_id'))
        batch_op.drop_index(batch_op.f('ix_financial_statements_fiscal_year'))
        batch_op.drop_index(batch_op.f('ix_financial_statements_created_at'))

    op.drop_table('financial_statements')
    with op.batch_alter_table('chatbot_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chatbot_messages_user_id'))
        batch_op.drop_index(batch_op.f('ix_chatbot_messages_session_id'))
        batch_op.drop_index(batch_op.f('ix_chatbot_messages_created_at'))

    op.drop_table('chatbot_messages')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_resource_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_resource_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_request_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_organization_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('token_blocklist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_token_blocklist_jti'))

    op.drop_table('token_blocklist')
    with op.batch_alter_table('system_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_logs_request_id'))
        batch_op.drop_index(batch_op.f('ix_system_logs_logger_name'))
        batch_op.drop_index(batch_op.f('ix_system_logs_level'))
        batch_op.drop_index(batch_op.f('ix_system_logs_created_at'))

    op.drop_table('system_logs')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_name'))
        batch_op.drop_index(batch_op.f('ix_organizations_is_active'))
        batch_op.drop_index(batch_op.f('ix_organizations_created_at'))

    op.drop_table('organizations')
    # ### end Alembic commands ###
